POST http://localhost:9070/users
Content-Type: application/json
X-Test: f 
// headers normally start with X- ???
{
    "username": "CoolZero",
    "password": "Hatfgbgrjktjkrtjktrjtsdhusiuerhgju",
    "email": "bloop"
}